engines:
  eslint:
    enabled: true
    checks:
      import/no-unresolved:
        enabled: false
      new-cap:
        enabled: false
ratings:
  paths:
  - 'src/**'
  - 'bin/**'
  - 'test/**'
exclude_patterns:
- "doc/**"
- "frontend/**"
- "doc/**"
- "**.md"
- "yarn.lock"
- "package.json"
- "node_modules"